name: Lint
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/jameshiew/toolbox/images/luaci:421900a1cf6f2f3e577cf84ec1f72a74d30eee35e4088c28ccadcdba5918b7a3
    steps:
      - uses: actions/checkout@v2.3.4
      - run: |
          luacheck .
      - run: |
          stylua --check .
